name: .NET Core

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  Solution_Name: LibraryManagement.sln
  Test_Project_Path: LibraryManagement.Tests/LibraryManagement.Tests.csproj

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Execute unit tests
      run: dotnet test ${{ env.Test_Project_Path }} --no-build --verbosity normal

    - name: Build Solution
      run: dotnet build ${{ env.Solution_Name }} --no-restore
